import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ui/theme-provider";
import QueryProviders from "@/providers/QueryClientProvider";
import SheetProvider from "@/providers/SheetProvider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`grid grid-rows-[auto_1fr_auto] w-full min-h-screen ${inter.className}`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <QueryProviders>
              <SheetProvider></SheetProvider>

              <section className="w-full">
                <Header></Header>
              </section>

              <main className="w-full h-full overflow-hidden">{children}</main>
              <section className="w-full">
                <Footer></Footer>
              </section>
            </QueryProviders>
          </ThemeProvider>
          <Toaster></Toaster>
        </body>
      </html>
    </ClerkProvider>
  );
}
